
on:
  push:
    branches:
      - main
env:
    PACKAGE_NAME: plugin_loopstructural
permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release

          
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
  package:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build for pypi and upload
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/lachlangrose/${{env.PACKAGE_NAME}}/actions/workflows/releaser.yml/dispatches \
          -d '{"ref":"main"}'
        
