name: "🚀 Releaser"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PROJECT_FOLDER: "loopstructural"
  PYTHON_VERSION: 3.9


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Get source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: "pip"
        cache-dependency-path: "requirements/packaging.txt"
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system requirements
      run: |
        sudo apt update
        sudo apt install qt5-qmake qttools5-dev-tools

    - name: Install Python requirements
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/packaging.txt

    # - name: Compile translations
    #   run: lrelease ${{ env.PROJECT_FOLDER }}/resources/i18n/*.ts

    - name : Get current changelog for ${GITHUB_REF/refs\/tags\//}
      run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md


    - name: Deploy plugin
      env:
        OSGEO_USERNAME: ${{ secrets.OSGEO_USERNAME }}
        OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}

      run: >-
        qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --allow-uncommitted-changes
        --create-plugin-repo
        --osgeo-username "$env:OSGEO_USERNAME"
        --osgeo-password "$env:OSGEO_PASSWORD"

